name: Scan Repositories with Grype CSV

on:
  workflow_dispatch:
    inputs:
      repos:
        description: 'URLs of repositories to scan, separated by spaces'
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan repositories
      run: |
        repos="${{ github.event.inputs.repos }}"
        for repo in $repos; do
          repo_name=$(basename $repo)
          git clone $repo temp-repo
          cd temp-repo
          grype . -o json > ../${repo_name}-scan.json
          cd ..
          rm -rf temp-repo
        done

    - name: Process scan results
      run: |
        echo "REPO NAME,INSTALLED,FIXED-IN,TYPE,VULNERABILITY,SEVERITY" > scan-results.csv
        for file in *-scan.json; do
          repo_name=$(basename $file -scan.json)
          jq -r --arg repo_name "$repo_name" '.matches[] | "\($repo_name),\(.artifact.name),\(.artifact.version),\(.artifact.type),\(.vulnerability.id),\(.vulnerability.severity)"' $file >> scan-results.csv
        done

    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: scan-results.csv
