name: Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta el escaneo diariamente a medianoche
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'URL del repositorio a escanear'
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repo_url }}

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Run Grype scan
      id: grype
      run: grype ${{ github.workspace }} -o json > results.json

    - name: Generate Excel report
      run: |
        go run generate_report.go
      env:
        REPO_URL: ${{ github.event.inputs.repo_url }}
