name: Scan Repositories for Vulnerabilities

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta la acción diariamente a medianoche
  workflow_dispatch:
    inputs:
      repo_urls:
        description: 'URLs de los repositorios a escanear'
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan repositories
      run: |
        mkdir -p results
        for repo in ${{ github.event.inputs.repo_urls }}; do
          grype $repo -o json > results/$(basename $repo).json
        done

    - name: Generate Excel report
      run: |
        go run generate_report.go
      env:
        REPO_URLS: ${{ github.event.inputs.repo_urls }}

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: vulnerability-report
        path: report.xlsx
