name: Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * *' # Programado para ejecutarse diariamente a medianoche
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan repositories
      run: |
        repos=("https://github.com/user/repo1" "https://github.com/user/repo2") # Reemplaza con las URLs de los repositorios a escanear
        results=()
        for repo in "${repos[@]}"; do
          git clone "$repo" repo_temp
          cd repo_temp
          grype . -o json > ../result.json
          cd ..
          vulnerabilities=$(cat result.json)
          results+=("{\"repo\": \"$repo\", \"vulnerabilities\": $vulnerabilities}")
          rm -rf repo_temp result.json
        done
        echo "[${results[*]}]" > scan_results.json

    - name: Upload scan results
      uses: actions/upload-artifact@v2
      with:
        name: scan-results
        path: scan_results.json
