name: Vulnerability Scan

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: 'Comma-separated list of repository URLs to scan'
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan repositories
      run: |
        IFS=',' read -r -a repos <<< "${{ github.event.inputs.repositories }}"
        results=()
        for repo in "${repos[@]}"; do
          git clone "$repo" repo_temp
          cd repo_temp
          grype . -o json > ../result.json
          cd ..
          vulnerabilities=$(cat result.json)
          results+=("{\"repo\": \"$repo\", \"vulnerabilities\": $vulnerabilities}")
          rm -rf repo_temp result.json
        done
        echo "[${results[*]}]" > scan_results.json

    - name: Upload scan results
      uses: actions/upload-artifact@v2
      with:
        name: scan-results
        path: scan_results.json
