name: Scan Repositories with Grype

on:
  workflow_dispatch:
    inputs:
      repos:
        description: 'URLs of repositories to scan, separated by spaces'
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan repositories
      run: |
        repos="${{ github.event.inputs.repos }}"
        for repo in $repos; do
          git clone $repo temp-repo
          cd temp-repo
          grype . > ../${repo##*/}-scan.txt
          cd ..
          rm -rf temp-repo
        done

    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: scan-results
        path: '*.txt'
