name: txt Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * *' # Programa para que se ejecute diariamente a medianoche
  workflow_dispatch: # Permite ejecutar la acción manualmente

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan repositories
      run: |
        repos="URL_REPO1 URL_REPO2" # Reemplaza con las URLs de los repositorios a escanear
        for repo in $repos; do
          git clone $repo repo_temp
          cd repo_temp
          grype . > ../${repo##*/}_vulnerabilities.txt
          cd ..
          rm -rf repo_temp
        done

    - name: Upload scan results
      uses: actions/upload-artifact@v2
      with:
        name: scan-results
        path: *_vulnerabilities.txt
